apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-app
  template:
    metadata:
      labels:
        app: cats-app
    spec:
      containers:
      - name: cats-app
        image: cats-app:v1
---
apiVersion: v1
kind: Service
metadata:
  name: nestdip-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: cats-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001